export { default as ManagerDashboardPage } from './ManagerDashboardPage'
export { default as ManagerInvoicesPage } from './ManagerInvoicesPage'
export { default as ManagerLayout } from './ManagerLayout'
export { default as ManagerAddProductPage } from './ManagerAddProductPage'
export { default as ManagerEditProductPage } from './ManagerEditProductPage'
export { default as ManagerAddAttributePage } from './ManagerAddAttributePage'
export { default as ManagerInvoiceCard } from './components/invoices/ManagerInvoiceCard'
export { default as ManagerVouchersPage } from './ManagerVouchersPage'
