// Order Type Enum
export enum OrderType {
  NORMAL = 'NORMAL',
  PRE_ORDER = 'PRE-ORDER',
  MANUFACTURING = 'MANUFACTURING',
  RETURN = 'RETURN'
}

// Order Status Enum
export enum OrderStatus {
  PENDING = 'PENDING',
  WAITING_VERIFY = 'WAITING_VERIFY',
  VERIFIED = 'VERIFIED',
  APPROVE = 'APPROVE',
  APPROVED = 'APPROVED',
  REJECT = 'REJECT',
  REJECTED = 'REJECTED',
  WAITING_ASSIGN = 'WAITING_ASSIGN',
  ASSIGNED = 'ASSIGNED',
  MAKING = 'MAKING',
  PACKAGING = 'PACKAGING',
  PACKAGED = 'PACKAGED',
  PACKING = 'PACKING',
  COMPLETED = 'COMPLETED',
  CANCELED = 'CANCELED',
  WAITING_REFUND = 'WAITING_REFUND',
  REFUNDED = 'REFUNDED',
  SHIPPED = 'SHIPPED',
  PROCESSING = 'PROCESSING',
  ONBOARD = 'ONBOARD',
  DELIVERED = 'DELIVERED',
  DELIVERING = 'DELIVERING'
}

export const AssignmentOrderStatus = {
  PENDING: 'PENDING',
  ASSIGNED: 'ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED'
} as const
export type AssignmentOrderStatus =
  (typeof AssignmentOrderStatus)[keyof typeof AssignmentOrderStatus]
